### ISSUE TITLE
team scramble broken/requirements too high

### ISSUE THREAD

**Issue by itVictor** [Mikusch/tfgo#25]
teams went 10-0 without any scramble, either scrambler is broken or the requirement is too high (if it's the latter it should be like 3-5 rounds before scramble)

**Comment by Mikusch** [comment]
A scramble should definitely have happened there. Looking further into it, it seems to be a bug with  TF2's arena mode, which does not initiate a scramble without ``tf_arena_use_queue`` being set to ``1``. This is not going to be fun.

**Comment by FortyTwoFortyTwo** [comment]
Enabled team scramble from redsun's plugin

**Comment by Mikusch** [comment]
Forgot to close this. Team scrambling and half-time side switching is now a plugin feature with #31.
