### ISSUE TITLE
Suggestion: Disable the bomb after the bomb planters have won

### ISSUE THREAD

**Issue by Blazephlozard** [Mikusch/tfgo#26]
Right now, the bomb stays active, even if the round has ended. Then, it can blow up and kill players of the winning team. That seems a bit wrong, especially since death has such a big penalty here.

**Comment by Mikusch** [comment]
This is done intentionally because that is also how it works in CS:GO. I am not a huge fan of this suggestion as I would like to keep the bomb logic close to the actual game but am willing to look at what other people have to say.

**Comment by woisalreadytaken** [comment]
I like the way it is now, if you know the other team can't defuse the bomb you run away from it, just like in CS

**Comment by Blazephlozard** [comment]
Yeah, if that's how it is in CSGO, that's fine. I'd also guess hearing the ten second countdown music (which wasn't downloading before) would be a good tip-off to stay away before the new round starts.

**Comment by Mikusch** [comment]
Seeing how there's no new input I'm going to close this.
Keep in mind that the bomb also beeps faster during the 10 second time period so even with the music turned off you can still hear if it is close to explosion.
